export const SIREN_FRANCE_TRAVAIL = "130005481";

// eslint-disable-next-line no-shadow
export const enum TallyFormId {
  SERVICE_CREATION_FORM_ID = "mRGdpK",
}

export const FUNDED_SERVICES = {
  "12": {
    organism: "Conseil départemental de l’Aveyron",
    label: "Ce service est financé par le conseil départemental de l’Aveyron",
    slugs: [
      "ass-pour-droit-a-l-i-dwdv-microcredit-mobilite-lhjo",
      "ass-pour-droit-a-l-i-dwdv-microcredit-mobilite-mlhr",
      "ass-pour-droit-a-l-i-dwdv-microcredit-mobilite",
      "ass-pour-droit-a-l-i-dwdv-",
      "ass-pour-droit-a-l-i-dwdv--kivw",
      "ass-pour-droit-a-l-i-dwdv-microcredit-professi-vdlf",
      "ass-pour-droit-a-l-i-dwdv-microcredit-professi-dgnl",
      "ass-pour-droit-a-l-i-dwdv-microcredit-professi-jkaf",
      "ass-pour-droit-a-l-i-dwdv-microcredit-professi",
      "association-myriade-information-et-accom",
      "association-myriade-apprendre-le-francai",
      "comite-rouergat-daid-francais-langue-etra-ivkb",
      "comite-rouergat-daid-francais-langue-etra-zmxk",
      "comite-rouergat-daid-alphabetisation-lutt-mjwn",
      "comite-rouergat-daid-alphabetisation-lutt",
      "comite-rouergat-daid-francais-langue-etra",
      "comite-rouergat-daid-alphabetisation-lutt-sgcx",
      "comite-rouergat-daid-alphabetisation-lutt-sgcx",
      "comite-rouergat-daid-francais-langue-etra-yssh",
      "comite-rouergat-daid-francais-langue-etra-jsru",
      "centre-dinformation--tojo-information-et-accom",
      "vacances-familles-v--vacances-pour-tous",
      "village-12-ateliers-de-francais",
      "village-12-accompagnement-socia",
      "village-12-mobilite-des-demande",
      "acces-logement-inser-centre-dhebergement--hmvm",
    ],
  },
  "26": {
    organism: "Conseil départemental de la Drôme",
    label: "Ce service est financé par le conseil départemental de la Drôme",
    slugs: [
      "agir-innover-mobilis-on-a-des-projets",
      "agir-innover-mobilis-et-si-on-relevait-le-pfaj",
      "agir-innover-mobilis-et-si-on-relevait-le-kwyq",
      "agir-innover-mobilis-et-si-on-relevait-le-andd",
      "agir-innover-mobilis-et-si-on-relevait-le-gjsi",
      "agir-innover-mobilis-identification-des-m",
      "agir-innover-mobilis-identification-des-m-mulq",
      "agir-innover-mobilis-identification-des-m-wktt",
      "agir-innover-mobilis-identification-des-m-plbm",
      "agir-innover-mobilis-identification-des-m-wxsn",
      "ancre-et-si-on-decouvrait--ycqw",
      "ancre-et-si-on-decouvrait--gcmr",
      "ancre-et-si-on-decouvrait--zvmy",
      "ancre-et-si-on-decouvrait--otlp",
      "ancre-et-si-on-decouvrait--zglv",
      "archer-levee-des-freins-jin-wiia",
      "archer-levee-des-freins-jin-seis",
      "archer-levee-des-freins-jin-ltab",
      "archer-levee-des-freins-jin-nogy",
      "archer-levee-des-freins-jin-fhmn",
      "archer-levee-des-freins-jin-veqv",
      "archer-jinterroge-mon-activ",
      "archer-levee-des-freins-jin-cnjs",
      "bimbamjob-jlgu-vers-un-nouveau-depa",
      "bimbamjob-jlgu-vers-un-nouveau-depa-vyea",
      "bimbamjob-jlgu-vers-un-nouveau-depa-ulya",
      "cefora-sarl-cefora-vers-un-nouveau-depa",
      "cefora-sarl-cefora-vers-un-nouveau-depa-jope",
      "plateforme-dinsertio-et-si-on-decouvrait-",
      "plateforme-dinsertio-vers-lemploi",
      "plateforme-dinsertio-le-permis-de-conduir",
      "plateforme-dinsertio-preparation-et-accom-usqu",
      "germinal-07-jinterroge-mon-activ",
      "germinal-07-jinterroge-mon-activ-ohwe",
      "germinal-07-jinterroge-mon-activ-jvaz",
      "germinal-07-jinterroge-mon-activ-tasr",
      "germinal-07-jinterroge-mon-activ-bmht",
      "innovation-developpe-akuu-levee-des-freins-san-lbnw",
      "innovation-developpe-akuu-levee-des-freins-san",
      "innovation-developpe-akuu-levee-des-freins-san-eoen",
      "institut-national-de-eyjf-vers-un-nouveau-depa-mcri",
      "institut-national-de-eyjf-vers-un-nouveau-depa-vcqc",
      "institut-national-de-eyjf-vers-un-nouveau-depa-pnye",
      "institut-national-de-eyjf-vers-un-nouveau-depa-dfqc",
      "institut-national-de-eyjf-vers-un-nouveau-depa-mbng",
      "institut-national-de-eyjf-le-permis-de-conduir",
      "institut-national-de-eyjf-le-permis-de-conduir-qbki",
      "institut-national-de-eyjf-le-permis-de-conduir-scyr",
      "institut-national-de-eyjf-le-permis-de-conduir-fjre",
      "institut-national-de-eyjf-le-permis-de-conduir-qrra",
      "institut-promotions--identification-des-m-eyqd",
      "institut-promotions--identification-des-m-ckis",
      "institut-promotions--identification-des-m-wkpq",
      "institut-promotions--identification-des-m-ftlr",
      "institut-promotions--identification-des-m-qfod",
      "institut-promotions--identification-des-m-qsvi",
      "institut-promotions--identification-des-m-xjxo",
      "institut-promotions--et-si-on-relevait-le-xusy",
      "institut-promotions--et-si-on-relevait-le-ejsu",
      "institut-promotions--et-si-on-relevait-le-vsve",
      "institut-promotions--et-si-on-relevait-le-giyz",
      "institut-promotions--et-si-on-relevait-le-tsne",
      "institut-promotions--et-si-on-relevait-le-fpzu",
      "institut-promotions--et-si-on-relevait-le-jijd",
      "institut-promotions--levee-des-freins-san-bwps",
      "institut-promotions--levee-des-freins-san-nrpg",
      "institut-promotions--levee-des-freins-san-gsfl",
      "institut-promotions--levee-des-freins-san-iprt",
      "institut-promotions--levee-des-freins-san-ntgz",
      "institut-promotions--levee-des-freins-san-diya",
      "mobilite-07-26-permis-de-conduire-c-nrfs",
      "mobilite-07-26-permis-de-conduire-c-sfja",
      "mobilite-07-26-auto-ecole-insertion-pxjt",
      "mobilite-07-26-lacces-a-des-vehicul-smkc",
      "mobilite-07-26-lacces-a-des-vehicul",
      "mobilite-07-26-lacces-a-des-vehicul-tfmg",
      "mobilite-07-26-lacces-a-des-vehicul-kbds",
      "mobilite-07-26-lacces-a-des-vehicul-qaqa",
      "mobilite-07-26-lacces-a-des-vehicul-upjy",
      "ass-tremplin-inserti-permis-de-conduire-c-bjzn",
      "ass-tremplin-inserti-permis-de-conduire-c-imsn",
      "ass-tremplin-inserti-permis-de-conduire-c-uoro",
      "valence-services-et-si-on-decouvrait-",
      "valence-services-rsa-drome-accesentre-ikeb",
      "valence-services-rsa-drome-accesentre-eiba",
      "valence-services-rsa-drome-accesentre-xdyy",
      "valence-services-rsa-drome-accesentre-dfso",
      "valence-services-rsa-drome-accesentre-mwxr",
      "valence-services-rsa-drome-accesentre-dcab",
      "valence-services-rsa-drome-accesentre-jbxc",
      "valence-services-rsa-drome-accesentre-cmig",
      "valence-services-rsa-drome-accesentre-rwib",
      "valence-services-rsa-drome-accesentre-tall",
      "valence-services-rsa-arche-agglo-loca-njtl",
      "valence-services-rsa-arche-agglo-loca-zcpl",
      "valence-services-rsa-arche-agglo-loca-rovo",
      "valence-services-rsa-arche-agglo-loca",
      "valence-services-rsa-drome-accesentre-ombo",
      "valence-services-rsa-drome-accesentre-xxir",
      "valence-services-rsa-drome-accesentre-atpu",
      "valence-services-rsa-drome-accesentre-htsl",
      "valence-services-rsa-drome-accesentre-mmql",
      "valence-services-rsa-drome-accesentre-lrzt",
      "valence-services-rsa-drome-accesentre-adlk",
      "valence-services-rsa-drome-accesentre-ojtn",
      "valence-services-rsa-drome-accesentre-ebhy",
      "valence-services-rsa-drome-accesentre",
      "valence-services-rsa-porte-de-dromard",
      "valence-services-rsa-porte-de-dromard-ihlb",
      "valence-services-rsa-porte-de-dromard-upbw",
      "valence-services-rsa-porte-de-dromard-kiqh",
    ],
  },
};
